version: "3"
services:
  web:
    image: registry.gitlab.com/tpearl/tpearl-shop:latest
    ports:
      - "8080:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_API_SKIP_AUTH: ${VITE_API_SKIP_AUTH}
    restart: always

